### ISSUE TITLE
unicode strings cannot be stored

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/h5py_wrapper#10]
Storing a list of unicode string leads to the following h5py error:
`TypeError: No conversion path for dtype: dtype('<U1')`.

I haven't understood the background completely. If there is no workaround in h5py, we should at least build in some error catching / conversion code. This error can be reproduced with the additional test added in my personal branch unicode_strings.

**Comment by mschmidt87** [comment]
A simple way to turn a list of unicode string into ascii strings is this
`l2 = [n.encode('ascii', 'ignore') for n in l]`

**Comment by jakobj** [comment]
a potential problem with this is that it fails silently:
```python
>>> u'é'.encode('ascii', 'ignore')
''
>>> u'à'.encode('ascii', 'ignore')
''
```
so people would end up with "corrupted" labels or even worse, empty and hence unidentifyable labels. in my opinion we have two options: let the wrapper raise an exception to notify the user (which then has the chance to make sure he/she doesn't use unicode) or add an option to `add_to_h5` which defines the treatment of unicode strings (`'ignore'`, `'replace'`, `'xmlcharrefreplace'`). the default should be `'xmlcharrefreplace'` because it does not lead to unidentifyable labels:
```python
>>> u'é'.encode('ascii', 'xmlcharrefreplace')
'&#233;'
>>> u'à'.encode('ascii', 'xmlcharrefreplace')
'&#224;'
```

**Comment by mschmidt87** [comment]
The default option of encode is 'strict', which raises an error for the examples you posted, so using this as the default option with the other options available to the user would combine your two suggestions, wouldn't it?

However, is there anyway to retrieve the original unicode from this?
```
>>> u'à'.encode('ascii', 'xmlcharrefreplace')
'&#224;'
```

**Comment by mschmidt87** [comment]
Okay, I think our policy should be this:

- We should support unicode if it can be encoded in ASCII, i.e., if
    x.encode('ascii') does not throw an error.
   For this, we encode all unicode objects to ascii before saving. When the data is loaded, it is then loaded as a string. In the solution of #11 , we could make it possible to load the data as unicode again.

**Comment by mschmidt87** [comment]
I now changed this to utf-8 encoding, i.e.,
`x.encode('utf-8')`

See here for a documentation of string in HDF5: [http://docs.h5py.org/en/latest/strings.html](http://docs.h5py.org/en/latest/strings.html).

**Comment by jakobj** [comment]
Looks good. One thing I am confused about is, whether we want to allow storing of non-ascii strings like é. Because with this version of the code this is possible and leads to conversion to non-utf, xml code.

```python
>>> h5w.add_to_h5('test.h5', {'l': u'é'})
>>> h5w.load_h5('test.h5')
{u'l': '\xc3\xa9'}
```

But I think this is fine for the moment. We will add conversion back to unicode strings later.
