### ISSUE TITLE
Conversion scripts hangs instead of displaying help message when called without arguments

### ISSUE THREAD

**Issue by jakobj** [INM-6/h5py_wrapper#40]
If the conversion script is executed without arguments usage information should be printed. Instead, the script tries to read from stdin continously. I think this is caused by docopt since only optional arguments are specified. We should change at least `<files>` to non-optional.

**Comment by mschmidt87** [comment]
If I make the <files> to non-optional, then the command line option does not work anymore because it will then complain about the missing argument.

We could implement a switch like '--std-in' but I don't like this solution because it requires more action from the user.
There seems to be no proper way around this in UNIX, because stdin is designed to wait for something to happen. See [http://stackoverflow.com/questions/3762881/how-do-i-check-if-stdin-has-some-data](http://stackoverflow.com/questions/3762881/how-do-i-check-if-stdin-has-some-data)

`grep` shows a similar behavior: Try `grep 'something'` for example.
So, I close without fixing.
